// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Style", "IDE0044:読み取り専用修飾子を追加します", Justification = "<保留中>", Scope = "member", Target = "~F:DragAndDropModule.DragAndDropReciever._control")]
[assembly: SuppressMessage("Style", "IDE0044:読み取り専用修飾子を追加します", Justification = "<保留中>", Scope = "member", Target = "~F:ImageViewer5.FormMain._logger")]
[assembly: SuppressMessage("Style", "IDE0044:読み取り専用修飾子を追加します", Justification = "<保留中>", Scope = "member", Target = "~F:ImageViewer5.ImageControl.ImageMainFrame._isFormClosingForFileListThread")]
[assembly: SuppressMessage("Style", "IDE0044:読み取り専用修飾子を追加します", Justification = "<保留中>", Scope = "member", Target = "~F:ViewImageModule.ViewImageFrameControlForm._form")]
[assembly: SuppressMessage("Style", "IDE0044:読み取り専用修飾子を追加します", Justification = "<保留中>", Scope = "member", Target = "~F:ViewImageModule.ViewImageFrameControlForm._logger")]
[assembly: SuppressMessage("CodeQuality", "IDE0051:使用されていないプライベート メンバーを削除する", Justification = "<保留中>", Scope = "member", Target = "~M:ImageViewer5.ImageControl.ImageMainFrame.SubProcMain")]
[assembly: SuppressMessage("CodeQuality", "IDE0051:使用されていないプライベート メンバーを削除する", Justification = "<保留中>", Scope = "member", Target = "~M:ViewImageModule.ViewImageFunction_FitInnerToFrame.InnerControlSizeFitFrameControl(System.Drawing.Size,System.Drawing.Size,System.Drawing.Size)~System.Int32")]
[assembly: SuppressMessage("CodeQuality", "IDE0051:使用されていないプライベート メンバーを削除する", Justification = "<保留中>", Scope = "member", Target = "~M:ViewImageModule.ViewImageFunction_FitInnerToFrame.IsImageSizeMoreThanFrameSize(System.Drawing.Size,System.Drawing.Size)~System.Boolean")]
[assembly: SuppressMessage("Style", "IDE1006:命名スタイル", Justification = "<保留中>", Scope = "member", Target = "~M:ImageViewer5.ImageControl.ImageMainFrame.doLoopFileListSubThread")]
[assembly: SuppressMessage("Style", "IDE0060:未使用のパラメーターを削除します", Justification = "<保留中>", Scope = "member", Target = "~M:ViewImageModule.ViewImageFunction_FitInnerToFrame.InnerControlSizeFitFrameControl(System.Drawing.Size,System.Drawing.Size,System.Drawing.Size)~System.Int32")]
[assembly: SuppressMessage("Style", "IDE0059:値の不必要な代入", Justification = "<保留中>", Scope = "member", Target = "~M:ImageViewer5.ImageViewerArgs.ReadArgs")]
[assembly: SuppressMessage("CodeQuality", "IDE0052:読み取られていないプライベート メンバーを削除", Justification = "<保留中>", Scope = "member", Target = "~F:ImageViewer5.ApplySettings._nowImageMainFrame")]
[assembly: SuppressMessage("CodeQuality", "IDE0052:読み取られていないプライベート メンバーを削除", Justification = "<保留中>", Scope = "member", Target = "~F:ImageViewer5.ImageViewerArgs._baseArgs")]
[assembly: SuppressMessage("CodeQuality", "IDE0052:読み取られていないプライベート メンバーを削除", Justification = "<保留中>", Scope = "member", Target = "~F:ImageViewer5.ImageViewerArgs._frameSettingsList")]
[assembly: SuppressMessage("Style", "IDE0060:未使用のパラメーターを削除します", Justification = "<保留中>", Scope = "member", Target = "~M:ImageViewer5.ImageControl.ImageMainClass.InitializeValues(System.Collections.Generic.List{System.String})")]
[assembly: SuppressMessage("Style", "IDE0060:未使用のパラメーターを削除します", Justification = "<保留中>", Scope = "member", Target = "~M:ImageViewer5.ImageControl.ImageMainClass.ShowImageAfterInitialize(System.String)")]
[assembly: SuppressMessage("Style", "IDE0044:読み取り専用修飾子を追加します", Justification = "<保留中>", Scope = "member", Target = "~F:ImageViewer5.ApplySettings._formMain")]
[assembly: SuppressMessage("Style", "IDE0044:読み取り専用修飾子を追加します", Justification = "<保留中>", Scope = "member", Target = "~F:ImageViewer5.ApplySettings._logger")]
[assembly: SuppressMessage("Style", "IDE0044:読み取り専用修飾子を追加します", Justification = "<保留中>", Scope = "member", Target = "~F:ImageViewer5.ApplySettings._nowImageMainFrame")]
[assembly: SuppressMessage("Style", "IDE0044:読み取り専用修飾子を追加します", Justification = "<保留中>", Scope = "member", Target = "~F:ImageViewer5.ImageViewerArgs._baseArgs")]
[assembly: SuppressMessage("Style", "IDE0044:読み取り専用修飾子を追加します", Justification = "<保留中>", Scope = "member", Target = "~F:ImageViewer5.ImageViewerArgs._frameSettingsList")]
[assembly: SuppressMessage("Style", "IDE0044:読み取り専用修飾子を追加します", Justification = "<保留中>", Scope = "member", Target = "~F:ImageViewer5.ImageViewerArgs._logger")]
[assembly: SuppressMessage("Style", "IDE0017:オブジェクトの初期化を簡略化します", Justification = "<保留中>", Scope = "member", Target = "~M:ImageViewer5.FormMain.#ctor(System.String[])")]
[assembly: SuppressMessage("CodeQuality", "IDE0051:使用されていないプライベート メンバーを削除する", Justification = "<保留中>", Scope = "member", Target = "~M:ImageViewer5.ApplySettings.GetDictValueBool(System.Collections.Generic.Dictionary{System.String,System.Object},System.String)~System.Int32")]
[assembly: SuppressMessage("CodeQuality", "IDE0051:使用されていないプライベート メンバーを削除する", Justification = "<保留中>", Scope = "member", Target = "~M:ImageViewer5.ApplySettings.GetDictValueInt(System.Collections.Generic.Dictionary{System.String,System.Object},System.String)~System.Int32")]
[assembly: SuppressMessage("CodeQuality", "IDE0051:使用されていないプライベート メンバーを削除する", Justification = "<保留中>", Scope = "member", Target = "~M:ImageViewer5.ApplySettings.GetDictValueStr(System.Collections.Generic.Dictionary{System.String,System.Object},System.String)~System.String")]
[assembly: SuppressMessage("CodeQuality", "IDE0052:読み取られていないプライベート メンバーを削除", Justification = "<保留中>", Scope = "member", Target = "~F:ImageViewer5.ImageControl.ImageMainClass._draggerFrame")]
[assembly: SuppressMessage("CodeQuality", "IDE0052:読み取られていないプライベート メンバーを削除", Justification = "<保留中>", Scope = "member", Target = "~F:ImageViewer5.ImageControl.ImageMainClass._formDraggerByForm")]
[assembly: SuppressMessage("CodeQuality", "IDE0052:読み取られていないプライベート メンバーを削除", Justification = "<保留中>", Scope = "member", Target = "~F:ImageViewer5.ImageControl.ImageMainClass._formDraggerByFrame")]
[assembly: SuppressMessage("CodeQuality", "IDE0052:読み取られていないプライベート メンバーを削除", Justification = "<保留中>", Scope = "member", Target = "~F:ImageViewer5.ImageControl.ImageMainClass._transparentFormSwitch")]
[assembly: SuppressMessage("Style", "IDE0044:読み取り専用修飾子を追加します", Justification = "<保留中>", Scope = "member", Target = "~F:ImageViewer5.ImageControl.Function.ImageFrameArgs._imageMainFrame")]
[assembly: SuppressMessage("CodeQuality", "IDE0052:読み取られていないプライベート メンバーを削除", Justification = "<保留中>", Scope = "member", Target = "~F:ImageViewer5.ImageControl.Function.ImageFrameArgs._imageMainFrame")]
[assembly: SuppressMessage("CodeQuality", "IDE0052:読み取られていないプライベート メンバーを削除", Justification = "<保留中>", Scope = "member", Target = "~F:ImageViewer5.ImageControl.Function.ImageFrameArgs._logger")]
[assembly: SuppressMessage("Style", "IDE0044:読み取り専用修飾子を追加します", Justification = "<保留中>", Scope = "member", Target = "~F:ImageViewer5.ImageControl.Function.ImageFrameArgs._logger")]
[assembly: SuppressMessage("Style", "IDE0044:読み取り専用修飾子を追加します", Justification = "<保留中>", Scope = "member", Target = "~F:ImageViewer5.ImageControl.Function.ViewImageSlideShow._imageMainFrame")]
[assembly: SuppressMessage("Style", "IDE0044:読み取り専用修飾子を追加します", Justification = "<保留中>", Scope = "member", Target = "~F:ImageViewer5.ImageControl.Function.ViewImageSlideShow._logger")]
[assembly: SuppressMessage("Style", "IDE0017:オブジェクトの初期化を簡略化します", Justification = "<保留中>", Scope = "member", Target = "~M:ImageViewer5.ImageControl.Function.ViewImageSlideShow.#ctor(AppLoggerModule.AppLogger,ImageViewer5.ImageControl.ImageMainFrame)")]
[assembly: SuppressMessage("Style", "IDE0059:値の不必要な代入", Justification = "<保留中>", Scope = "member", Target = "~M:ImageViewer5.ImageControl.ImageMainClass.InitializeValues(System.Collections.Generic.List{System.String})")]
[assembly: SuppressMessage("Style", "IDE0060:未使用のパラメーターを削除します", Justification = "<保留中>", Scope = "member", Target = "~M:ImageViewer5.ImageControl.Function.ImageFrameArgs.ExecuteFunctionByArgs(System.Collections.Generic.Dictionary{System.String,System.Object})")]
[assembly: SuppressMessage("Style", "IDE0059:値の不必要な代入", Justification = "<保留中>", Scope = "member", Target = "~M:ImageViewer5.Program.Main(System.String[])")]
[assembly: SuppressMessage("CodeQuality", "IDE0052:読み取られていないプライベート メンバーを削除", Justification = "<保留中>", Scope = "member", Target = "~F:ImageViewer5.MainFrameManager._nowImageMainFrame")]
[assembly: SuppressMessage("Style", "IDE0059:値の不必要な代入", Justification = "<保留中>", Scope = "member", Target = "~M:ImageViewer5.MainFrameManager.AdjustSizeAndLocation(System.Int32)")]
[assembly: SuppressMessage("Style", "IDE0017:オブジェクトの初期化を簡略化します", Justification = "<保留中>", Scope = "member", Target = "~M:ImageViewer5.ImageControl.Function.ViewImageSlideShow.GetNewTimer~System.Windows.Forms.Timer")]
[assembly: SuppressMessage("Style", "IDE0017:オブジェクトの初期化を簡略化します", Justification = "<保留中>", Scope = "member", Target = "~M:ImageViewer5.MainFrameManager.CreateImageMainFrame(System.Int32)~ImageViewer5.ImageControl.ImageMainFrame")]
