// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Style", "IDE0044:読み取り専用修飾子を追加します", Justification = "<保留中>", Scope = "member", Target = "~F:PlayMovieForm.FormMainPlayMoview._logger")]
[assembly: SuppressMessage("Style", "IDE0044:読み取り専用修飾子を追加します", Justification = "<保留中>", Scope = "member", Target = "~F:PlayMovieForm.FormMainPlayMoview._movieList")]
[assembly: SuppressMessage("Style", "IDE1006:命名スタイル", Justification = "<保留中>", Scope = "member", Target = "~M:PlayMovieForm.FormMainPlayMoview.btnPlay_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:命名スタイル", Justification = "<保留中>", Scope = "member", Target = "~M:PlayMovieForm.FormMainPlayMoview.btnStop_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE0044:読み取り専用修飾子を追加します", Justification = "<保留中>", Scope = "member", Target = "~F:PlayMovieForm.VideoPlayer._logger")]
[assembly: SuppressMessage("Style", "IDE0044:読み取り専用修飾子を追加します", Justification = "<保留中>", Scope = "member", Target = "~F:PlayMovieForm.VideoPlayer._panel")]
[assembly: SuppressMessage("Style", "IDE0017:オブジェクトの初期化を簡略化します", Justification = "<保留中>", Scope = "member", Target = "~M:PlayMovieForm.FormMainPlayMoview.#ctor")]
[assembly: SuppressMessage("Style", "IDE0017:オブジェクトの初期化を簡略化します", Justification = "<保留中>", Scope = "member", Target = "~M:PlayMovieForm.VideoPlayer.Play")]
[assembly: SuppressMessage("CodeQuality", "IDE0052:読み取られていないプライベート メンバーを削除", Justification = "<保留中>", Scope = "member", Target = "~F:PlayMovieForm.VideoPlayerDefault._moviePath")]
[assembly: SuppressMessage("CodeQuality", "IDE0052:読み取られていないプライベート メンバーを削除", Justification = "<保留中>", Scope = "member", Target = "~F:PlayMovieForm.VideoPlayerDefault._pictureBox")]
[assembly: SuppressMessage("CodeQuality", "IDE0052:読み取られていないプライベート メンバーを削除", Justification = "<保留中>", Scope = "member", Target = "~F:PlayMovieForm.VideoPlayerVlc._moviePath")]
[assembly: SuppressMessage("CodeQuality", "IDE0052:読み取られていないプライベート メンバーを削除", Justification = "<保留中>", Scope = "member", Target = "~F:PlayMovieForm.VideoPlayerVlc._pictureBox")]
[assembly: SuppressMessage("Style", "IDE1006:命名スタイル", Justification = "<保留中>", Scope = "member", Target = "~M:PlayMovieForm.FormMainPlayMoview.btnPlay_MouseClick(System.Object,System.Windows.Forms.MouseEventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:命名スタイル", Justification = "<保留中>", Scope = "member", Target = "~M:PlayMovieForm.FormMainPlayMoview.btnStop_MouseClick(System.Object,System.Windows.Forms.MouseEventArgs)")]
[assembly: SuppressMessage("Style", "IDE0018:インライン変数宣言", Justification = "<保留中>", Scope = "member", Target = "~M:PlayMovieForm.VideoPlayerMediaFoundation.Timer_Tick(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE0017:オブジェクトの初期化を簡略化します", Justification = "<保留中>", Scope = "member", Target = "~M:PlayMovieForm.VideoPlayerMediaFoundation.Play")]
[assembly: SuppressMessage("Style", "IDE0018:インライン変数宣言", Justification = "<保留中>", Scope = "member", Target = "~M:PlayMovieForm.VideoPlayerMf.CreateMediaSource")]
[assembly: SuppressMessage("Style", "IDE0018:インライン変数宣言", Justification = "<保留中>", Scope = "member", Target = "~M:PlayMovieForm.VideoPlayerMf.CreateTopology")]
[assembly: SuppressMessage("Style", "IDE0018:インライン変数宣言", Justification = "<保留中>", Scope = "member", Target = "~M:PlayMovieForm.VideoPlayerMf.CreateTopologyBranch(PlayMovieForm.VideoPlayerMf.IMFTopology,PlayMovieForm.VideoPlayerMf.IMFMediaSource,PlayMovieForm.VideoPlayerMf.IMFPresentationDescriptor,PlayMovieForm.VideoPlayerMf.IMFStreamDescriptor)")]
[assembly: SuppressMessage("CodeQuality", "IDE0052:読み取られていないプライベート メンバーを削除", Justification = "<保留中>", Scope = "member", Target = "~F:PlayMovieForm.VideoPlayerDefault._videoControl")]
[assembly: SuppressMessage("CodeQuality", "IDE0052:読み取られていないプライベート メンバーを削除", Justification = "<保留中>", Scope = "member", Target = "~F:PlayMovieForm.VideoPlayerVlc._videoView")]
[assembly: SuppressMessage("Style", "IDE0059:値の不必要な代入", Justification = "<保留中>", Scope = "member", Target = "~M:PlayMovieForm.VideoPlayerMf.CreateMediaSource")]
[assembly: SuppressMessage("CodeQuality", "IDE0051:使用されていないプライベート メンバーを削除する", Justification = "<保留中>", Scope = "member", Target = "~F:PlayMovieForm.VideoPlayerMf.MF_VIDEO_RENDERER_DRAW_TO_HWND")]
[assembly: SuppressMessage("CodeQuality", "IDE0051:使用されていないプライベート メンバーを削除する", Justification = "<保留中>", Scope = "member", Target = "~M:PlayMovieForm.VideoPlayerMf.GetParameters(PlayMovieForm.VideoPlayerMf.MFASync@,PlayMovieForm.VideoPlayerMf.MFAsyncCallbackQueue@)")]
[assembly: SuppressMessage("CodeQuality", "IDE0051:使用されていないプライベート メンバーを削除する", Justification = "<保留中>", Scope = "member", Target = "~M:PlayMovieForm.VideoPlayerMf.Invoke(PlayMovieForm.VideoPlayerMf.IMFAsyncResult)")]
[assembly: SuppressMessage("Style", "IDE0044:読み取り専用修飾子を追加します", Justification = "<保留中>", Scope = "member", Target = "~F:PlayMovieForm.VideoPlayerDefault._logger")]
[assembly: SuppressMessage("Style", "IDE0044:読み取り専用修飾子を追加します", Justification = "<保留中>", Scope = "member", Target = "~F:PlayMovieForm.VideoPlayerDefault._videoControl")]
[assembly: SuppressMessage("Style", "IDE0044:読み取り専用修飾子を追加します", Justification = "<保留中>", Scope = "member", Target = "~F:PlayMovieForm.VideoPlayerMediaFoundation._frameRate")]
[assembly: SuppressMessage("Style", "IDE0044:読み取り専用修飾子を追加します", Justification = "<保留中>", Scope = "member", Target = "~F:PlayMovieForm.VideoPlayerMediaFoundation._logger")]
[assembly: SuppressMessage("Style", "IDE0044:読み取り専用修飾子を追加します", Justification = "<保留中>", Scope = "member", Target = "~F:PlayMovieForm.VideoPlayerMediaFoundation._pictureBox")]
[assembly: SuppressMessage("Style", "IDE0044:読み取り専用修飾子を追加します", Justification = "<保留中>", Scope = "member", Target = "~F:PlayMovieForm.VideoPlayerMf._logger")]
[assembly: SuppressMessage("Style", "IDE0044:読み取り専用修飾子を追加します", Justification = "<保留中>", Scope = "member", Target = "~F:PlayMovieForm.VideoPlayerMf._videoControl")]
[assembly: SuppressMessage("Style", "IDE0044:読み取り専用修飾子を追加します", Justification = "<保留中>", Scope = "member", Target = "~F:PlayMovieForm.VideoPlayerVlc._libVLC")]
[assembly: SuppressMessage("Style", "IDE0044:読み取り専用修飾子を追加します", Justification = "<保留中>", Scope = "member", Target = "~F:PlayMovieForm.VideoPlayerVlc._logger")]
[assembly: SuppressMessage("Style", "IDE0044:読み取り専用修飾子を追加します", Justification = "<保留中>", Scope = "member", Target = "~F:PlayMovieForm.VideoPlayerVlc._mediaPlayer")]
[assembly: SuppressMessage("Style", "IDE0044:読み取り専用修飾子を追加します", Justification = "<保留中>", Scope = "member", Target = "~F:PlayMovieForm.VideoPlayerVlc._videoView")]
