// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Style", "IDE0044:読み取り専用修飾子を追加します", Justification = "<保留中>", Scope = "member", Target = "~F:FileSenderApp.ButtonsGroup._colMax")]
[assembly: SuppressMessage("Style", "IDE0044:読み取り専用修飾子を追加します", Justification = "<保留中>", Scope = "member", Target = "~F:FileSenderApp.ButtonsGroup._orderPriority_RowCol")]
[assembly: SuppressMessage("Style", "IDE0044:読み取り専用修飾子を追加します", Justification = "<保留中>", Scope = "member", Target = "~F:FileSenderApp.ButtonsGroup._rowMax")]
[assembly: SuppressMessage("CodeQuality", "IDE0052:読み取られていないプライベート メンバーを削除", Justification = "<保留中>", Scope = "member", Target = "~F:FileSenderApp.ButtonsGroup._tmpHeight")]
[assembly: SuppressMessage("Style", "IDE0044:読み取り専用修飾子を追加します", Justification = "<保留中>", Scope = "member", Target = "~F:FileSenderApp.FileSenderSettingValues.ColorPicker._cd")]
[assembly: SuppressMessage("Style", "IDE0044:読み取り専用修飾子を追加します", Justification = "<保留中>", Scope = "member", Target = "~F:FileSenderApp.FormFileSenderApp._logger")]
[assembly: SuppressMessage("Style", "IDE0044:読み取り専用修飾子を追加します", Justification = "<保留中>", Scope = "member", Target = "~F:FileSenderApp.FormFileSenderApp._senderMainTab")]
[assembly: SuppressMessage("CodeQuality", "IDE0052:読み取られていないプライベート メンバーを削除", Justification = "<保留中>", Scope = "member", Target = "~F:FileSenderApp.SendButton._index")]
[assembly: SuppressMessage("Style", "IDE0044:読み取り専用修飾子を追加します", Justification = "<保留中>", Scope = "member", Target = "~F:FileSenderApp.SenderMainTab._logger")]
[assembly: SuppressMessage("Style", "IDE0044:読み取り専用修飾子を追加します", Justification = "<保留中>", Scope = "member", Target = "~F:FileSenderApp.SenderMainTab._parentForm")]
[assembly: SuppressMessage("Style", "IDE0044:読み取り専用修飾子を追加します", Justification = "<保留中>", Scope = "member", Target = "~F:FileSenderApp.SenderMainTab._renameControl")]
[assembly: SuppressMessage("Style", "IDE0044:読み取り専用修飾子を追加します", Justification = "<保留中>", Scope = "member", Target = "~F:FileSenderApp.SenderMainTab._rightTabPage")]
[assembly: SuppressMessage("CodeQuality", "IDE0052:読み取られていないプライベート メンバーを削除", Justification = "<保留中>", Scope = "member", Target = "~F:FileSenderApp.SenderMainTab._rightTabPage")]
[assembly: SuppressMessage("Style", "IDE0044:読み取り専用修飾子を追加します", Justification = "<保留中>", Scope = "member", Target = "~F:FileSenderApp.SenderMainTab._tabControl")]
[assembly: SuppressMessage("Style", "IDE0044:読み取り専用修飾子を追加します", Justification = "<保留中>", Scope = "member", Target = "~F:FileSenderApp.SenderMainTab.NEW_TAB_NAME")]
[assembly: SuppressMessage("Style", "IDE0060:未使用のパラメーターを削除します", Justification = "<保留中>", Scope = "member", Target = "~M:AppLoggerModule.AppLogger.GetErrorMessages(System.Boolean,System.Boolean)~System.Collections.Generic.List{System.String}")]
[assembly: SuppressMessage("Style", "IDE0060:未使用のパラメーターを削除します", Justification = "<保留中>", Scope = "member", Target = "~M:AppLoggerModule.AppLogger.GetLastErrorMessagesAsString(System.Int32,System.Boolean)~System.String")]
[assembly: SuppressMessage("Style", "IDE1006:命名スタイル", Justification = "<保留中>", Scope = "member", Target = "~M:AppLoggerModule.AppLogger.hasAlert~System.Boolean")]
[assembly: SuppressMessage("Style", "IDE1006:命名スタイル", Justification = "<保留中>", Scope = "member", Target = "~M:AppLoggerModule.AppLogger.hasError~System.Boolean")]
[assembly: SuppressMessage("Style", "IDE0019:パターン マッチングを使用します", Justification = "<保留中>", Scope = "member", Target = "~M:FileSenderApp.ButtonsGroup.Button_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:命名スタイル", Justification = "<保留中>", Scope = "member", Target = "~M:FileSenderApp.FileSenderSettingValues.ButtonSettingGroup.buttonColorPicker_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE0017:オブジェクトの初期化を簡略化します", Justification = "<保留中>", Scope = "member", Target = "~M:FileSenderApp.FileSenderSettingValues.ColorPicker.#ctor")]
[assembly: SuppressMessage("Style", "IDE0017:オブジェクトの初期化を簡略化します", Justification = "<保留中>", Scope = "member", Target = "~M:FileSenderApp.FormFileSenderApp.#ctor")]
[assembly: SuppressMessage("Style", "IDE1006:命名スタイル", Justification = "<保留中>", Scope = "member", Target = "~M:FileSenderApp.FormFileSenderApp.button1_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:命名スタイル", Justification = "<保留中>", Scope = "member", Target = "~M:FileSenderApp.FormFileSenderButtonSetting.buttonApply_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:命名スタイル", Justification = "<保留中>", Scope = "member", Target = "~M:FileSenderApp.FormFileSenderButtonSetting.buttonCancel_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE0017:オブジェクトの初期化を簡略化します", Justification = "<保留中>", Scope = "member", Target = "~M:FileSenderApp.SenderMainTab.AddTabPage")]
[assembly: SuppressMessage("Style", "IDE0059:値の不必要な代入", Justification = "<保留中>", Scope = "member", Target = "~M:FileSenderApp.SenderMainTab.InitializeButtonGroup")]
[assembly: SuppressMessage("Style", "IDE0044:読み取り専用修飾子を追加します", Justification = "<保留中>", Scope = "member", Target = "~F:FileSenderApp.FileSenderSettingValues.ButtonSettingGroup._resetColor")]
[assembly: SuppressMessage("CodeQuality", "IDE0052:読み取られていないプライベート メンバーを削除", Justification = "<保留中>", Scope = "member", Target = "~F:FileSenderApp.FileSenderSettingValues.ButtonSettingGroup._sendButton")]
[assembly: SuppressMessage("Style", "IDE0044:読み取り専用修飾子を追加します", Justification = "<保留中>", Scope = "member", Target = "~F:FileSenderApp.FormFileSenderApp._jsonStream")]
[assembly: SuppressMessage("Style", "IDE0044:読み取り専用修飾子を追加します", Justification = "<保留中>", Scope = "member", Target = "~F:FileSenderApp.SenderMainTab._ObjectName")]
[assembly: SuppressMessage("CodeQuality", "IDE0051:使用されていないプライベート メンバーを削除する", Justification = "<保留中>", Scope = "member", Target = "~F:FileSenderApp.SenderMainTab._ObjectName")]
[assembly: SuppressMessage("CodeQuality", "IDE0051:使用されていないプライベート メンバーを削除する", Justification = "<保留中>", Scope = "member", Target = "~F:FileSenderApp.SenderMainTab._rightTabPage")]
[assembly: SuppressMessage("Style", "IDE0060:未使用のパラメーターを削除します", Justification = "<保留中>", Scope = "member", Target = "~M:AppLoggerModuleB.AppLoggerB.GetErrorMessages(System.Boolean,System.Boolean)~System.Collections.Generic.List{System.String}")]
[assembly: SuppressMessage("Style", "IDE0060:未使用のパラメーターを削除します", Justification = "<保留中>", Scope = "member", Target = "~M:AppLoggerModuleB.AppLoggerB.GetLastErrorMessagesAsString(System.Int32,System.Boolean)~System.String")]
[assembly: SuppressMessage("Style", "IDE1006:命名スタイル", Justification = "<保留中>", Scope = "member", Target = "~M:AppLoggerModuleB.AppLoggerB.hasAlert~System.Boolean")]
[assembly: SuppressMessage("Style", "IDE1006:命名スタイル", Justification = "<保留中>", Scope = "member", Target = "~M:AppLoggerModuleB.AppLoggerB.hasError~System.Boolean")]
[assembly: SuppressMessage("Style", "IDE1006:命名スタイル", Justification = "<保留中>", Scope = "member", Target = "~M:FileSenderApp.FileSenderSettingValues.ButtonSettingGroup.buttonColorReset_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("CodeQuality", "IDE0051:使用されていないプライベート メンバーを削除する", Justification = "<保留中>", Scope = "member", Target = "~M:FileSenderApp.FormFileSenderApp.BackUpFile(System.String)")]
[assembly: SuppressMessage("Style", "IDE0059:値の不必要な代入", Justification = "<保留中>", Scope = "member", Target = "~M:FileSenderApp.FormFileSenderApp.ClearTabControl")]
[assembly: SuppressMessage("CodeQuality", "IDE0051:使用されていないプライベート メンバーを削除する", Justification = "<保留中>", Scope = "member", Target = "~M:FileSenderApp.FormFileSenderApp.CreateDefaultInfoDict")]
[assembly: SuppressMessage("Style", "IDE0059:値の不必要な代入", Justification = "<保留中>", Scope = "member", Target = "~M:FileSenderApp.FormFileSenderApp.CreateDefaultInfoDict")]
[assembly: SuppressMessage("Style", "IDE0059:値の不必要な代入", Justification = "<保留中>", Scope = "member", Target = "~M:FileSenderApp.FormFileSenderApp.FormFileSenderApp_FormClosing(System.Object,System.Windows.Forms.FormClosingEventArgs)")]
[assembly: SuppressMessage("Style", "IDE0059:値の不必要な代入", Justification = "<保留中>", Scope = "member", Target = "~M:FileSenderApp.FormFileSenderApp.SettingFileInitialize")]
[assembly: SuppressMessage("Style", "IDE0059:値の不必要な代入", Justification = "<保留中>", Scope = "member", Target = "~M:FileSenderApp.SenderMainTab.AddTabPage")]
[assembly: SuppressMessage("Style", "IDE0059:値の不必要な代入", Justification = "<保留中>", Scope = "member", Target = "~M:FileSenderApp.SenderMainTab.InitializeButtonGroupSingle(FileSenderApp.ButtonsGroup)")]
[assembly: SuppressMessage("Style", "IDE0059:値の不必要な代入", Justification = "<保留中>", Scope = "member", Target = "~M:FileSenderApp.SenderMainTab.TabControl_Selecting(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("CodeQuality", "IDE0052:読み取られていないプライベート メンバーを削除", Justification = "<保留中>", Scope = "member", Target = "~F:FileSenderApp.FileSenderSetting.ButtonSettingGroup._sendButton")]
[assembly: SuppressMessage("CodeQuality", "IDE0052:読み取られていないプライベート メンバーを削除", Justification = "<保留中>", Scope = "member", Target = "~F:FileSenderApp.FileSenderSettingValues._logger")]
[assembly: SuppressMessage("CodeQuality", "IDE0052:読み取られていないプライベート メンバーを削除", Justification = "<保留中>", Scope = "member", Target = "~F:FileSenderApp.FileSenderSettingValues._partsSettingDict")]
[assembly: SuppressMessage("CodeQuality", "IDE0052:読み取られていないプライベート メンバーを削除", Justification = "<保留中>", Scope = "member", Target = "~F:FileSenderApp.FileSenderSettingValues._tabSettingDict")]
[assembly: SuppressMessage("Style", "IDE1006:命名スタイル", Justification = "<保留中>", Scope = "member", Target = "~M:FileSenderApp.FileSenderSetting.ButtonSettingGroup.buttonColorPicker_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:命名スタイル", Justification = "<保留中>", Scope = "member", Target = "~M:FileSenderApp.FileSenderSetting.ButtonSettingGroup.buttonColorReset_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE0059:値の不必要な代入", Justification = "<保留中>", Scope = "member", Target = "~M:FileSenderApp.FormFileSenderApp.AddPageBySetting")]
[assembly: SuppressMessage("Style", "IDE0044:読み取り専用修飾子を追加します", Justification = "<保留中>", Scope = "member", Target = "~F:FileSenderApp.FileSenderSetting.ButtonSettingGroup._resetColor")]
[assembly: SuppressMessage("Style", "IDE0044:読み取り専用修飾子を追加します", Justification = "<保留中>", Scope = "member", Target = "~F:FileSenderApp.FileSenderSettingValues._logger")]
[assembly: SuppressMessage("Style", "IDE0044:読み取り専用修飾子を追加します", Justification = "<保留中>", Scope = "member", Target = "~F:FileSenderApp.FileSenderSettingValues._partsSettingDict")]
[assembly: SuppressMessage("Style", "IDE0044:読み取り専用修飾子を追加します", Justification = "<保留中>", Scope = "member", Target = "~F:FileSenderApp.FileSenderSettingValues._tabSettingDict")]
[assembly: SuppressMessage("Style", "IDE0044:読み取り専用修飾子を追加します", Justification = "<保留中>", Scope = "member", Target = "~F:FileSenderApp.FormFileSenderApp.isOutputSetting")]
[assembly: SuppressMessage("Style", "IDE0044:読み取り専用修飾子を追加します", Justification = "<保留中>", Scope = "member", Target = "~F:FileSenderApp.SenderMainTab._checkBoxControl")]
[assembly: SuppressMessage("Style", "IDE0044:読み取り専用修飾子を追加します", Justification = "<保留中>", Scope = "member", Target = "~F:FileSenderApp.DataBridgeFromExternal._logger")]
[assembly: SuppressMessage("Style", "IDE0059:値の不必要な代入", Justification = "<保留中>", Scope = "member", Target = "~M:FileSenderApp.FormFileSenderApp.FormFileSenderApp_FormClosed(System.Object,System.Windows.Forms.FormClosedEventArgs)")]
[assembly: SuppressMessage("Style", "IDE0028:コレクションの初期化を簡略化します", Justification = "<保留中>", Scope = "member", Target = "~M:FileSenderApp.FormFileSenderApp.SetUndo(System.String,System.String,System.Boolean)")]
[assembly: SuppressMessage("Style", "IDE0017:オブジェクトの初期化を簡略化します", Justification = "<保留中>", Scope = "member", Target = "~M:FileSenderApp.Job.JobManager.AddJobItem(System.Collections.Generic.Dictionary{System.String,System.Object})")]
[assembly: SuppressMessage("Style", "IDE0044:読み取り専用修飾子を追加します", Justification = "<保留中>", Scope = "member", Target = "~F:FileSenderApp.Job.JobManager._jobItemList")]
[assembly: SuppressMessage("Style", "IDE0044:読み取り専用修飾子を追加します", Justification = "<保留中>", Scope = "member", Target = "~F:FileSenderApp.Job.JobManager._keyList")]
[assembly: SuppressMessage("Style", "IDE0044:読み取り専用修飾子を追加します", Justification = "<保留中>", Scope = "member", Target = "~F:FileSenderApp.Job.JobManager._logger")]
[assembly: SuppressMessage("Style", "IDE0044:読み取り専用修飾子を追加します", Justification = "<保留中>", Scope = "member", Target = "~F:FileSenderApp.Job.JobManager._redoUndoList")]
[assembly: SuppressMessage("Style", "IDE0059:値の不必要な代入", Justification = "<保留中>", Scope = "member", Target = "~M:FileSenderApp.Job.JobManager.GetRedoItem~FileSenderApp.Job.JobItem")]
[assembly: SuppressMessage("Style", "IDE0059:値の不必要な代入", Justification = "<保留中>", Scope = "member", Target = "~M:FileSenderApp.Job.JobManager.GetUndoItem~FileSenderApp.Job.JobItem")]
[assembly: SuppressMessage("Style", "IDE1006:命名スタイル", Justification = "<保留中>", Scope = "member", Target = "~M:FileSenderApp.FormFileSenderApp.buttonRedo_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:命名スタイル", Justification = "<保留中>", Scope = "member", Target = "~M:FileSenderApp.FormFileSenderApp.buttonUndo_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("CodeQuality", "IDE0052:読み取られていないプライベート メンバーを削除", Justification = "<保留中>", Scope = "member", Target = "~F:FileSenderApp.DataBridgeFromExternal._logger")]
[assembly: SuppressMessage("Style", "IDE0059:値の不必要な代入", Justification = "<保留中>", Scope = "member", Target = "~M:FileSenderApp.FormFileSenderApp.AdjustWindowAtTabPageButtonsHeight(System.Int32)")]
